### ISSUE TITLE
Allow to impersonate another user

### ISSUE THREAD

**Issue by buchi** [4teamwork/ftw.tokenauth#9]
We need the possibility to authenticate as an arbitrary user. Use-case: A third-party application wants to create content in the context of the currently logged-in user.

Proposed approach:
- To be able to impersonate, the user who has issued the service key must have a specific permission, e.g. 'Manage portal' or a new one 'ftw.tokenauth: Impersonate'.
- The userid to impersonate to is passed in the JWT token with the `sub` claim when requesting an access token.
- Currently the service key is looked up by userid and client id. In an impersonate scenario we would no longer pass the userid of the service key issuer but the userid of the user we want to impersonate. The client id should be unique though and thus sufficient for service key lookup.
- We need to store the userid in the stored access token because the authenticated user is not necessarily the same as the service key issuer.

@lukasgraf Can you check if you agree with that approach or maybe you want to propose something different?

**Comment by lukasgraf** [comment]
@buchi sounds good to me - I think I need to ponder a bit more on the details, and read the relevant specs again, but on the whole I think the way you describe it is how impersonation is meant to be implemented in OAuth2.

When implementing the current functionality, I did (vaguely) keep the impersonation use-case in the back of my mind, and if I remember correctly, exactly the lookup of the service key by userid *and* client ID was something that didn't feel quite right in that regard.

I'll look into this some more and get back to you.
